.TH "activation.ActivationRequest" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
activation.ActivationRequest
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModel\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "str \fBcode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBactivation\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str activation\&.ActivationRequest\&.code\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBactivation\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
