.TH "activation.ActivationCodeCreate" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
activation.ActivationCodeCreate
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModel\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "UUID \fBuser_id\fP"
.br
.ti -1c
.RI "str \fBcode\fP"
.br
.ti -1c
.RI "datetime \fBexpires_at\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBactivation\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str activation\&.ActivationCodeCreate\&.code\fC [static]\fP"

.PP
Definition at line \fB8\fP of file \fBactivation\&.py\fP\&.
.SS "datetime activation\&.ActivationCodeCreate\&.expires_at\fC [static]\fP"

.PP
Definition at line \fB9\fP of file \fBactivation\&.py\fP\&.
.SS "UUID activation\&.ActivationCodeCreate\&.user_id\fC [static]\fP"

.PP
Definition at line \fB7\fP of file \fBactivation\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
