.TH "activation.ActivationCodeInDB" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
activation.ActivationCodeInDB
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModel\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "UUID \fBid\fP"
.br
.ti -1c
.RI "UUID \fBuser_id\fP"
.br
.ti -1c
.RI "str \fBcode\fP"
.br
.ti -1c
.RI "datetime \fBexpires_at\fP"
.br
.ti -1c
.RI "Optional \fBused_at\fP = None"
.br
.ti -1c
.RI "datetime \fBcreated_at\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBactivation\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "str activation\&.ActivationCodeInDB\&.code\fC [static]\fP"

.PP
Definition at line \fB14\fP of file \fBactivation\&.py\fP\&.
.SS "datetime activation\&.ActivationCodeInDB\&.created_at\fC [static]\fP"

.PP
Definition at line \fB17\fP of file \fBactivation\&.py\fP\&.
.SS "datetime activation\&.ActivationCodeInDB\&.expires_at\fC [static]\fP"

.PP
Definition at line \fB15\fP of file \fBactivation\&.py\fP\&.
.SS "UUID activation\&.ActivationCodeInDB\&.id\fC [static]\fP"

.PP
Definition at line \fB12\fP of file \fBactivation\&.py\fP\&.
.SS "Optional activation\&.ActivationCodeInDB\&.used_at = None\fC [static]\fP"

.PP
Definition at line \fB16\fP of file \fBactivation\&.py\fP\&.
.SS "UUID activation\&.ActivationCodeInDB\&.user_id\fC [static]\fP"

.PP
Definition at line \fB13\fP of file \fBactivation\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
