.TH "models/activation.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models/activation.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBactivation\&.ActivationCodeCreate\fP"
.br
.ti -1c
.RI "class \fBactivation\&.ActivationCodeInDB\fP"
.br
.ti -1c
.RI "class \fBactivation\&.ActivationRequest\fP"
.br
.ti -1c
.RI "class \fBactivation\&.ActivationResponse\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBactivation\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
