.TH "auth" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
auth
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBget_current_user\fP (HTTPBasicCredentials credentials=Depends(\fBsecurity\fP))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsecurity\fP = HTTPBasic()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "auth\&.get_current_user (HTTPBasicCredentials  credentials = \fCDepends(\fBsecurity\fP)\fP)"

.PP
.nf
Dependency to get current authenticated user
.fi
.PP
 
.PP
Definition at line \fB8\fP of file \fBauth\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "auth\&.security = HTTPBasic()"

.PP
Definition at line \fB6\fP of file \fBauth\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
