.TH "dependencies/auth.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dependencies/auth.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBauth\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBauth\&.get_current_user\fP (HTTPBasicCredentials credentials=Depends(\fBsecurity\fP))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBauth\&.security\fP = HTTPBasic()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
