.TH "core/config.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/config.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconfig\&.Settings\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconfig\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconfig\&.settings\fP = \fBSettings\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
