.TH "config" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBsettings\fP = \fBSettings\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "config\&.settings = \fBSettings\fP()"

.PP
Definition at line \fB31\fP of file \fBconfig\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
