.TH "db/connection.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
db/connection.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBconnection\&.DatabasePool\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBconnection\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconnection\&.db\fP = \fBDatabasePool\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
