.TH "services/email_service.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services/email_service.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBemail_service\&.EmailService\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBemail_service\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBemail_service\&.logger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBemail_service\&.email_service\fP = \fBEmailService\fP()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
