.TH "email_service" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
email_service
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEmailService\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.ti -1c
.RI "\fBemail_service\fP = \fBEmailService\fP()"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "email_service\&.email_service = \fBEmailService\fP()"

.PP
Definition at line \fB46\fP of file \fBemail_service\&.py\fP\&.
.SS "email_service\&.logger = logging\&.getLogger(__name__)"

.PP
Definition at line \fB9\fP of file \fBemail_service\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
