.TH "exceptions.UserAlreadyExistsError" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.UserAlreadyExistsError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Exception raised when a user already exists
.fi
.PP
 
.PP
Definition at line \fB4\fP of file \fBexceptions\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
