.TH "core/exceptions.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
core/exceptions.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBexceptions\&.UserAlreadyExistsError\fP"
.br
.ti -1c
.RI "class \fBexceptions\&.UserNotFoundError\fP"
.br
.ti -1c
.RI "class \fBexceptions\&.InvalidActivationCodeError\fP"
.br
.ti -1c
.RI "class \fBexceptions\&.UserAlreadyActiveError\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBexceptions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBexceptions\&.setup_exception_handlers\fP (app)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
