.TH "exceptions" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInvalidActivationCodeError\fP"
.br
.ti -1c
.RI "class \fBUserAlreadyActiveError\fP"
.br
.ti -1c
.RI "class \fBUserAlreadyExistsError\fP"
.br
.ti -1c
.RI "class \fBUserNotFoundError\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsetup_exception_handlers\fP (app)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "exceptions\&.setup_exception_handlers ( app)"

.PP
.nf
Configure exception handlers for the FastAPI application
.fi
.PP
 
.PP
Definition at line \fB21\fP of file \fBexceptions\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
