.TH "exceptions.InvalidActivationCodeError" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exceptions.InvalidActivationCodeError
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SH "Detailed Description"
.PP 

.PP
.nf
Exception raised when the activation code is invalid or expired
.fi
.PP
 
.PP
Definition at line \fB12\fP of file \fBexceptions\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
