.TH "main" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBlifespan\fP (FastAPI \fBapp\fP)"
.br
.ti -1c
.RI "\fBhealth_check\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBapp\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "main\&.health_check ()"

.PP
.nf
Health check endpoint
.fi
.PP
 
.PP
Definition at line \fB32\fP of file \fBmain\&.py\fP\&.
.SS "main\&.lifespan (FastAPI app)"

.PP
Definition at line \fB8\fP of file \fBmain\&.py\fP\&.
.SH "Variable Documentation"
.PP 
.SS "main\&.app"
\fBInitial value:\fP.PP
.nf
1 =  FastAPI(
2     title="Registration API",
3     description="User registration and activation API",
4     version="1\&.0\&.0",
5     lifespan=lifespan
6 )
.fi

.PP
Definition at line \fB18\fP of file \fBmain\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
