.TH "md_README" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_README \- README 
.PP
#1 - Clone the repository git clone https://github.com/dradenvandewind/registration-api.git cd registration-api
.SH "2 - You need generate a secret key"
.PP
\&./GenerateSecretKey\&.sh
.SH "3 -1 Build and Run"
.PP
docker compose up -d --build
.PP
or
.SH "3- 2  Start all services"
.PP
docker compose up -d
.SH "4 - Access API documentation with your web browser"
.PP
http://localhost:8000/docs
.PP
#5 - Run tests docker compose exec api pytest -v --cov=app
.PP
#6 - Check logs docker compose logs -f api
.PP
#7 Stop and remove Volume docker compose down -v 
