.TH "api/v1/endpoints/registration.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api/v1/endpoints/registration.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBregistration\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "None \fBregistration\&._validate_password\fP (str password)"
.br
.ti -1c
.RI "\fBregistration\&.register_user\fP (UserCreate user_data, BackgroundTasks background_tasks)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBregistration\&.router\fP = APIRouter(prefix='/registration', tags=['registration'])"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
