.TH "router" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
router
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBrouter\fP = APIRouter(prefix='/v1')"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "router\&.router = APIRouter(prefix='/v1')"

.PP
Definition at line \fB4\fP of file \fBrouter\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
