.TH "api/v1/router.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api/v1/router.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBrouter\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBrouter\&.router\fP = APIRouter(prefix='/v1')"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
