.TH "security.PasswordHandler" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
security.PasswordHandler
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "str \fBhash_password\fP (str password)"
.br
.ti -1c
.RI "bool \fBverify_password\fP (str plain_password, str hashed_password)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Password hash manager using bcrypt directly
.fi
.PP
 
.PP
Definition at line \fB12\fP of file \fBsecurity\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS " str security\&.PasswordHandler\&.hash_password (str password)\fC [static]\fP"

.PP
.nf
Hash a password with bcrypt
.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBsecurity\&.py\fP\&.
.SS " bool security\&.PasswordHandler\&.verify_password (str plain_password, str hashed_password)\fC [static]\fP"

.PP
.nf
Check if password matches the hash
.fi
.PP
 
.PP
Definition at line \fB39\fP of file \fBsecurity\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
