.TH "test_security.TestPasswordHandler" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_security.TestPasswordHandler
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_hash_password_success\fP (self)"
.br
.ti -1c
.RI "\fBtest_hash_password_with_long_password\fP (self)"
.br
.ti -1c
.RI "\fBtest_hash_password_exception_handling\fP (self)"
.br
.ti -1c
.RI "\fBtest_verify_password_success\fP (self)"
.br
.ti -1c
.RI "\fBtest_verify_password_wrong_password\fP (self)"
.br
.ti -1c
.RI "\fBtest_verify_password_exception_handling\fP (self)"
.br
.ti -1c
.RI "\fBtest_verify_password_invalid_hash\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests for PasswordHandler class
.fi
.PP
 
.PP
Definition at line \fB13\fP of file \fBtest_security\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "test_security\&.TestPasswordHandler\&.test_hash_password_exception_handling ( self)"

.PP
.nf
Test exception handling in hash_password
Covers line 48 (exception raising)

.fi
.PP
 
.PP
Definition at line \fB59\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_hash_password_success ( self)"

.PP
.nf
Test successful password hashing
.fi
.PP
 
.PP
Definition at line \fB16\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_hash_password_with_long_password ( self)"

.PP
.nf
Test hashing a password longer than 72 bytes
Covers line 47-48 (truncation warning and logic)

.fi
.PP
 
.PP
Definition at line \fB33\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_verify_password_exception_handling ( self)"

.PP
.nf
Test exception handling in verify_password
Covers line 59 (return False on exception)

.fi
.PP
 
.PP
Definition at line \fB96\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_verify_password_invalid_hash ( self)"

.PP
.nf
Test verification with invalid hash format
Covers line 59 (exception handling)

.fi
.PP
 
.PP
Definition at line \fB110\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_verify_password_success ( self)"

.PP
.nf
Test successful password verification
.fi
.PP
 
.PP
Definition at line \fB71\fP of file \fBtest_security\&.py\fP\&.
.SS "test_security\&.TestPasswordHandler\&.test_verify_password_wrong_password ( self)"

.PP
.nf
Test verification with wrong password
.fi
.PP
 
.PP
Definition at line \fB83\fP of file \fBtest_security\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
