.TH "test_main.TestIntegration" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_main.TestIntegration
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_app_lifespan_integration\fP (self)"
.br
.ti -1c
.RI "\fBtest_app_routes_accessible\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Integration tests for the whole app
.fi
.PP
 
.PP
Definition at line \fB173\fP of file \fBtest_main\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "test_main\&.TestIntegration\&.test_app_lifespan_integration ( self)"

.PP
.nf
Integration test for app lifespan using httpx\&.AsyncClient

.fi
.PP
 
.PP
Definition at line \fB177\fP of file \fBtest_main\&.py\fP\&.
.SS "test_main\&.TestIntegration\&.test_app_routes_accessible ( self)"

.PP
.nf
Test that main routes are accessible using httpx\&.AsyncClient
.fi
.PP
 
.PP
Definition at line \fB194\fP of file \fBtest_main\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
