.TH "test_user_repository.TestUserRepositoryUpdatePassword" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_user_repository.TestUserRepositoryUpdatePassword
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_update_password_success\fP (self, user_repository, sample_user_id)"
.br
.ti -1c
.RI "\fBtest_update_password_nonexistent_user\fP (self, user_repository, sample_user_id)"
.br
.ti -1c
.RI "\fBtest_update_password_different_users\fP (self, user_repository)"
.br
.ti -1c
.RI "\fBtest_update_password_multiple_calls_same_user\fP (self, user_repository, sample_user_id)"
.br
.ti -1c
.RI "\fBtest_update_password_with_special_characters\fP (self, user_repository, sample_user_id)"
.br
.ti -1c
.RI "\fBtest_update_password_db_error\fP (self, user_repository, sample_user_id)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests for update_password method (lines 33-35)
.fi
.PP
 
.PP
Definition at line \fB203\fP of file \fBtest_user_repository\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_db_error ( self,  user_repository,  sample_user_id)"

.PP
.nf
Test database error during update_password
Ensures error propagation from line 35

.fi
.PP
 
.PP
Definition at line \fB359\fP of file \fBtest_user_repository\&.py\fP\&.
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_different_users ( self,  user_repository)"

.PP
.nf
Test updating passwords for different users
Ensures user_id parameter is used correctly (lines 33-35)

.fi
.PP
 
.PP
Definition at line \fB257\fP of file \fBtest_user_repository\&.py\fP\&.
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_multiple_calls_same_user ( self,  user_repository,  sample_user_id)"

.PP
.nf
Test updating password multiple times for same user
Covers lines 33-35 with repeated calls

.fi
.PP
 
.PP
Definition at line \fB303\fP of file \fBtest_user_repository\&.py\fP\&.
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_nonexistent_user ( self,  user_repository,  sample_user_id)"

.PP
.nf
Test updating password for a user that doesn't exist
Should still execute (UPDATE 0 rows)
Covers lines 33-35

.fi
.PP
 
.PP
Definition at line \fB234\fP of file \fBtest_user_repository\&.py\fP\&.
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_success ( self,  user_repository,  sample_user_id)"

.PP
.nf
Test successfully updating a user's password
Covers lines 33-35

.fi
.PP
 
.PP
Definition at line \fB207\fP of file \fBtest_user_repository\&.py\fP\&.
.SS "test_user_repository\&.TestUserRepositoryUpdatePassword\&.test_update_password_with_special_characters ( self,  user_repository,  sample_user_id)"

.PP
.nf
Test password update with special characters
Covers lines 33-35 with edge case input

.fi
.PP
 
.PP
Definition at line \fB337\fP of file \fBtest_user_repository\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
