.TH "test_security.TestSingletonInstance" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_security.TestSingletonInstance
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_password_handler_singleton\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Tests for the singleton instance
.fi
.PP
 
.PP
Definition at line \fB265\fP of file \fBtest_security\&.py\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "test_security\&.TestSingletonInstance\&.test_password_handler_singleton ( self)"

.PP
.nf
Test that password_handler is a singleton instance
.fi
.PP
 
.PP
Definition at line \fB268\fP of file \fBtest_security\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
