.TH "services/user_service.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
services/user_service.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuser_service\&.UserService\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBuser_service\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuser_service\&.logger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
