.TH "models/user.py" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
models/user.py
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBuser\&.UserCreate\fP"
.br
.ti -1c
.RI "class \fBuser\&.UserInDB\fP"
.br
.ti -1c
.RI "class \fBuser\&.UserResponse\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBuser\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBuser\&.PASSWORD_MIN_LENGTH\fP = 4"
.br
.ti -1c
.RI "int \fBuser\&.PASSWORD_MAX_LENGTH\fP = 4"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
