.TH "user_service" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_service
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUserService\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBlogger\fP = logging\&.getLogger(__name__)"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "user_service\&.logger = logging\&.getLogger(__name__)"

.PP
Definition at line \fB9\fP of file \fBuser_service\&.py\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
