.TH "user.UserResponse" 3 "Version v1.0" "registration-api" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user.UserResponse
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseModel\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "UUID \fBid\fP"
.br
.ti -1c
.RI "EmailStr \fBemail\fP"
.br
.ti -1c
.RI "bool \fBis_active\fP"
.br
.ti -1c
.RI "datetime \fBcreated_at\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBuser\&.py\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "datetime user\&.UserResponse\&.created_at\fC [static]\fP"

.PP
Definition at line \fB22\fP of file \fBuser\&.py\fP\&.
.SS "EmailStr user\&.UserResponse\&.email\fC [static]\fP"

.PP
Definition at line \fB20\fP of file \fBuser\&.py\fP\&.
.SS "UUID user\&.UserResponse\&.id\fC [static]\fP"

.PP
Definition at line \fB19\fP of file \fBuser\&.py\fP\&.
.SS "bool user\&.UserResponse\&.is_active\fC [static]\fP"

.PP
Definition at line \fB21\fP of file \fBuser\&.py\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for registration-api from the source code\&.
